"use strict";

/*
 * Compatibility entry points for older hosted UI code. Review-only exports are
 * generated by the plugin's own tb_detail_new component methods. This script
 * never replaces page Blob/JSZip constructors, prototypes or setters and never
 * enables a page-wide transformation window after a download event.
 */
(function installQq1000BuyerShowDownloadPatch() {
    if (window.__QQ1000_BUYER_SHOW_DOWNLOAD_PATCH_INSTALLED__) return;
    window.__QQ1000_BUYER_SHOW_DOWNLOAD_PATCH_INSTALLED__ = true;

    // Explicit pure conversion for legacy callers; current review exporters
    // read content/append.content fields directly to preserve the buyer's words.
    function cleanLine(value) {
        return String(value || "")
            .replace(/&nbsp;?/gi, " ")
            .replace(/\u00a0/g, " ")
            .replace(/[\t ]+/g, " ")
            .trim();
    }

    function sanitizeBuyerShowText(value) {
        const original = String(value == null ? "" : value).replace(/\r\n?/g, "\n");
        const lines = original.split("\n");
        const reviews = [];
        let captureMode = "";
        let recognized = false;

        function pushReview(line) {
            const cleaned = cleanLine(line);
            if (cleaned && cleaned !== "-" && cleaned !== "无评价内容") reviews.push(cleaned);
        }

        lines.forEach(line => {
            const cleaned = cleanLine(line);
            if (/^===\s*(?:首次评价|追加评价)\s*===$/.test(cleaned)) {
                recognized = true;
                captureMode = "block";
                return;
            }
            if (/^===/.test(cleaned)) {
                recognized = true;
                captureMode = "";
                return;
            }
            if (/^-{3,}$/.test(cleaned)) {
                recognized = true;
                captureMode = "";
                return;
            }

            const direct = cleaned.match(/^(?:评论内容|评价内容|内容评价|首评内容|首次评价内容|追评内容|追加评价内容|追加评论内容)\s*[:：]\s*(.*)$/i);
            if (direct) {
                recognized = true;
                pushReview(direct[1]);
                captureMode = "label";
                return;
            }

            const metadata = /^(?:评论\d+|买家昵称|用户昵称|会员等级|评论时间|评价时间|SKU(?:信息|规格)?|匿名评价|评价视频|视频链接|视频地址|图片地址|评论状态|AI内容|追评时间|追加评论时间|追加评价时间)\s*[:：]/i.test(cleaned);
            if (metadata) {
                recognized = true;
                if (captureMode === "label") captureMode = "";
                return;
            }

            if (captureMode && cleaned) pushReview(cleaned);
        });

        if (reviews.length) return reviews.join("\n");
        return recognized ? "" : original;
    }

    window.__QQ1000_SANITIZE_BUYER_SHOW_TEXT__ = sanitizeBuyerShowText;
    window.__QQ1000_PATCH_BUYER_SHOW_JSZIP__ = () => false;
    window.__QQ1000_REFRESH_BUYER_SHOW_PATCH__ = () => false;
})();
